[package]
name = "durabletask"
authors = ["Mike Nguyen<hey@mike.ee>"]
license.workspace = true
edition.workspace = true
publish = true
repository.workspace = true
version.workspace = true
description = "An implementation of the Durable Task Framework in Rust"
readme = "README.md"
homepage = "https://github.com/mikeee/durabletask-rust"
documentation = "https://docs.rs/durabletask"
keywords = ["durable", "task", "framework"]
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
durabletask-proto.workspace = true
prost-wkt-types.workspace = true
uuid = { version = "1.11.0", features = ["v4", "fast-rng"] }
gethostname = "0.5.0"
opentelemetry = "0.26.0"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
tokio = "1.41.1"
log = "0.4.22"
tonic = { workspace = true, features = ["tls", "tls-roots"]}
backon = "1.2.0"

