name: CI

on:
  push:
    branches:
      - main
      - release-*
    tags:
      - v*
  pull_request:
    branches:
      - main
      - release-*

jobs:
  deny:
    name: cargo-deny
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: cargo-deny
        uses: EmbarkStudios/cargo-deny-action@v1


  lint:
    name: Lint using rust(${{ matrix.rust }}) on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-latest"
        rust:
          - "stable"
          - "1.64.0" # Minimum supported rust version

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "25.x"

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cargo test
        run: cargo test -- --ignored

      - name: Cargo fmt
        run: cargo fmt -- --check

      - name: Cargo clippy
        run: cargo clippy -- -D warnings

      - name: Cargo doc
        run: cargo doc

  build:
    name: Build using rust(${{ matrix.rust }}) on ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-latest"
        rust:
          - "stable"
          - "1.64.0" # Minimum supported rust version

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "25.x"

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cargo build
        run: cargo build
