name: CI

on:
  push:
    branches:
      - main
      - release-*
    tags:
      - v*
  pull_request:
    branches:
      - main
      - release-*

jobs:
  deny:
    name: cargo-deny
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: cargo-deny
        uses: EmbarkStudios/cargo-deny-action@v2


  lint:
    name: Lint using rust(${{ matrix.rust-version }}) on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-latest"
        rust-version:
          - "stable"
          - "beta"
          - "nightly"
          - "1.70.0" # Minimum supported rust version

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: "25.x"

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          components: rustfmt, clippy
          toolchain: ${{ matrix.rust-version }}

      - name: Cargo test
        run: cargo test -- --include-ignored

      - name: Cargo fmt
        run: cargo fmt -- --check

      - name: Cargo clippy
        run: cargo clippy -- -D warnings

  build:
    name: Build using rust(${{ matrix.rust-version }}) on ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-latest"
        rust-version:
          - "stable"
          - "beta"
          - "nightly"
          - "1.70.0" # Minimum supported rust version

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: "25.x"

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust-version }}

      - name: Cargo build
        run: cargo build

  docs:
    name: Docs-rs test
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: -Dwarnings
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: "25.x"

      - name: Install Rust Toolchain (Nightly)
        uses: dtolnay/rust-toolchain@nightly

      - name: Install docs.rs with the same options
        uses: dtolnay/install@cargo-docs-rs

      - name: Run cargo rustdoc with docs.rs options
        run: cargo docs-rs